### ISSUE TITLE
Usage ;)

### ISSUE THREAD

**Issue by wusel42** [PowerPan/Freifunk-Node-Clients-stats#2]
Moin,

```
ffgt@map:~/ffmap-d3/build/nodestats$ /usr/bin/php5 /home/ffgt/ffmap-d3/build/nodestats/fillData.php
PHP Fatal error:  Call to undefined method System::addOnlineNode() in /home/ffgt/ffmap-d3/build/nodestats/class/Data.php on line 105
```

Indem ich "class/" in class/Data.php hinzufügte, lief's dann, bis:

```
creating '/home/ffgt/ffmap-d3/build/nodestats/class/../rrdData/system/system.rrd': No such file or directory1447369786:325:347opening '/home/ffgt/ffmap-d3/build/nodestats/class/../rrdData/system/system.rrd': No such file or directory
```

Nach ...

```
mkdir class/../rrdData/system
```

... lief's dann ;)

Außerdem muß graphs der Gruppe des Webservers gehören, sonst:

```
Could not save png to '/home/ffgt/ffmap-d3/build/nodestats/class/../graphs/system/system_1H_800_200.png'
```

Allerdings scheint was mit der Statistikeinsammlung nicht zu klappen: http://map.4830.org/nodestats/getNodeGraph.php?interval=1H&width=800&mac=60e327b80074 z. B. gibt mir keinen Traffic?

Ansonsten: Super, ich suche sowas (mit Auswertung der per-Node-Traffic-Daten) schon länger und wollte grade selbst was basteln, als ich Deinen Post im Forum sah!

**Comment by wattnpapa** [comment]
Ok ich teile das mal auf mehrere Issues auf ;)

#3 , #4 , #5
