### ISSUE TITLE
Aktualisierung der Statistikgraphen

### ISSUE THREAD

**Issue by mm-chen** [PowerPan/Freifunk-Node-Clients-stats#7]
Die Statistiken werden nur bei einem manuellen Reload der Webseite aktualisiert - nicht nach einem Minutenintervall.

**Comment by wattnpapa** [comment]
@mm-chen mach doch mal und mach dann einen pull request ;)

**Comment by mm-chen** [comment]
muss ich mal gucken, wann ich das mache... vielleicht am we
